version: "3.9"
services:
  master-container:
    build: /master
    image: master-img
    ports:
      - "5000:5000"
    container_name: master-container
  secondaries-container-1:
    build: /secondaries
    image: secondaries-img
    ports:
      - "5001:5000"
    container_name: secondaries-container-1
  secondaries-container-2:
    image: secondaries-img
    ports:
      - "5002:5000"
    container_name: secondaries-container-2
networks:
  default:
    name: master-secondaries-network
    driver: bridge